### ISSUE TITLE
[BUG] GitHub actions errors

### ISSUE THREAD

**Issue by KirolosMFahem** [yagnik2411/Quiz-Genius#86]
while reviewing the PR I found that GitHub get me error that 

and here's an example for PR 83 I got this error from Github CI

The failure occurred due to the following errors in the `lib/utils/profile_image_service.dart` file:

1. **URI Doesn't Exist**:
   - The import statement for `flutter/material.dart` has an extra space which makes it invalid.
   ```
   import 'package:flutter/material.dart ';
   ```

2. **Undefined Identifiers**:
   - The identifier `Colors` is undefined. This is due to the incorrect import statement mentioned above.

### Recent Changes

The recent commit that affected this file was:
- [d0e39b4](https://github.com/yagnik2411/Quiz-Genius/commit/d0e39b46f816e9e9b593a7fcbb49da1387c6630d): "Add Image Upload Feature".

### Suggested Fixes

1. Correct the import statement for `flutter/material.dart` by removing the extra space:
   ```dart
   import 'package:flutter/material.dart';
   ```

2. Ensure that the `Colors` class is properly referenced by fixing the import statement.

By correcting the import statement, the identifier `Colors` will be recognized, and the errors should be resolved.

**Comment by vijaykarthiktk** [comment]
lemme check

**Comment by KirolosMFahem** [comment]
new error message 

### Analysis of Error
The error in the logs indicates that the Android Gradle plugin requires Java 17, but the current environment is using Java 12. Here is the relevant log message:

```
Android Gradle plugin requires Java 17 to run. You are currently using Java 12.
Your current JDK is located in /opt/hostedtoolcache/jdk/12.0.2/x64
```

### Steps to Fix the Issue
1. **Update the Java Version in the CI/CD Pipeline:**
   - Modify the GitHub Actions workflow file to use Java 17 instead of Java 12.

### Example Update to GitHub Actions Workflow
Here is an example of how you can update the workflow file to use Java 17:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew build
```

### Summary
The failure is due to the Android Gradle plugin requiring Java 17. Updating the GitHub Actions workflow to use Java 17 should resolve the issue.
